//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class JSZX_ResourceEntities : DbContext
    {
        public JSZX_ResourceEntities()
            : base("name=JSZX_ResourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_Custom_Msg> T_Custom_Msg { get; set; }
        public DbSet<T_Interface> T_Interface { get; set; }
        public DbSet<T_Message> T_Message { get; set; }
        public DbSet<T_MyCollection> T_MyCollection { get; set; }
        public DbSet<T_Receive_Message> T_Receive_Message { get; set; }
        public DbSet<T_Res_Appendix> T_Res_Appendix { get; set; }
        public DbSet<T_Res_Qa> T_Res_Qa { get; set; }
        public DbSet<T_Res_Result> T_Res_Result { get; set; }
        public DbSet<T_Res_Score> T_Res_Score { get; set; }
        public DbSet<T_Res_Tag> T_Res_Tag { get; set; }
        public DbSet<T_Res_Type> T_Res_Type { get; set; }
        public DbSet<T_Resource> T_Resource { get; set; }
        public DbSet<T_ToChange> T_ToChange { get; set; }
        public DbSet<T_Version> T_Version { get; set; }
        public DbSet<Z_Admin> Z_Admin { get; set; }
        public DbSet<Z_Class> Z_Class { get; set; }
        public DbSet<Z_Class_Student> Z_Class_Student { get; set; }
        public DbSet<Z_Class_Student_Bak> Z_Class_Student_Bak { get; set; }
        public DbSet<Z_Class_Teacher> Z_Class_Teacher { get; set; }
        public DbSet<Z_Class_Teacher_Bak> Z_Class_Teacher_Bak { get; set; }
        public DbSet<Z_Course> Z_Course { get; set; }
        public DbSet<Z_Homework> Z_Homework { get; set; }
        public DbSet<Z_Homework_Appendix> Z_Homework_Appendix { get; set; }
        public DbSet<Z_Homework_Comment> Z_Homework_Comment { get; set; }
        public DbSet<Z_Homework_Student> Z_Homework_Student { get; set; }
        public DbSet<Z_Homework_Student_Comment> Z_Homework_Student_Comment { get; set; }
        public DbSet<Z_Menu> Z_Menu { get; set; }
        public DbSet<Z_PointRule> Z_PointRule { get; set; }
        public DbSet<Z_Review_Count> Z_Review_Count { get; set; }
        public DbSet<Z_Role> Z_Role { get; set; }
        public DbSet<Z_Role_Menu> Z_Role_Menu { get; set; }
        public DbSet<Z_School> Z_School { get; set; }
        public DbSet<Z_User> Z_User { get; set; }
        public DbSet<Z_UserPoint> Z_UserPoint { get; set; }
        public DbSet<V_MyCollection> V_MyCollection { get; set; }
        public DbSet<V_Public_Annex> V_Public_Annex { get; set; }
        public DbSet<V_Public_Type> V_Public_Type { get; set; }
        public DbSet<V_Version> V_Version { get; set; }
        public DbSet<View_Appendix> View_Appendix { get; set; }
        public DbSet<View_Qa> View_Qa { get; set; }
        public DbSet<View_Res_Appendix> View_Res_Appendix { get; set; }
        public DbSet<View_Resource> View_Resource { get; set; }
        public DbSet<View_Resource_20160622_bak> View_Resource_20160622_bak { get; set; }
        public DbSet<View_Resource_Top> View_Resource_Top { get; set; }
        public DbSet<View_Score> View_Score { get; set; }
    
        public virtual ObjectResult<AppendixByLike_Result> AppendixByLike(string likeStr, Nullable<System.DateTime> dt)
        {
            var likeStrParameter = likeStr != null ?
                new ObjectParameter("likeStr", likeStr) :
                new ObjectParameter("likeStr", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AppendixByLike_Result>("AppendixByLike", likeStrParameter, dtParameter);
        }
    
        public virtual ObjectResult<MyCollectionByLike_Result> MyCollectionByLike(string likeStr, Nullable<System.DateTime> dt)
        {
            var likeStrParameter = likeStr != null ?
                new ObjectParameter("likeStr", likeStr) :
                new ObjectParameter("likeStr", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MyCollectionByLike_Result>("MyCollectionByLike", likeStrParameter, dtParameter);
        }
    
        public virtual int Pro_ChangeTask(string iD, string fileName, string sourceFilePath, string targetFilePath, string retSql)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var sourceFilePathParameter = sourceFilePath != null ?
                new ObjectParameter("SourceFilePath", sourceFilePath) :
                new ObjectParameter("SourceFilePath", typeof(string));
    
            var targetFilePathParameter = targetFilePath != null ?
                new ObjectParameter("TargetFilePath", targetFilePath) :
                new ObjectParameter("TargetFilePath", typeof(string));
    
            var retSqlParameter = retSql != null ?
                new ObjectParameter("RetSql", retSql) :
                new ObjectParameter("RetSql", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_ChangeTask", iDParameter, fileNameParameter, sourceFilePathParameter, targetFilePathParameter, retSqlParameter);
        }
    
        public virtual int relatedAnnex(string relatedStr)
        {
            var relatedStrParameter = relatedStr != null ?
                new ObjectParameter("relatedStr", relatedStr) :
                new ObjectParameter("relatedStr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("relatedAnnex", relatedStrParameter);
        }
    
        public virtual ObjectResult<ResStatistics_Result> ResStatistics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ResStatistics_Result>("ResStatistics");
        }
    
        public virtual int SP_Delete(string tableName, string para1, string para2, string para3, string para4, string para5)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var para1Parameter = para1 != null ?
                new ObjectParameter("Para1", para1) :
                new ObjectParameter("Para1", typeof(string));
    
            var para2Parameter = para2 != null ?
                new ObjectParameter("Para2", para2) :
                new ObjectParameter("Para2", typeof(string));
    
            var para3Parameter = para3 != null ?
                new ObjectParameter("Para3", para3) :
                new ObjectParameter("Para3", typeof(string));
    
            var para4Parameter = para4 != null ?
                new ObjectParameter("Para4", para4) :
                new ObjectParameter("Para4", typeof(string));
    
            var para5Parameter = para5 != null ?
                new ObjectParameter("Para5", para5) :
                new ObjectParameter("Para5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete", tableNameParameter, para1Parameter, para2Parameter, para3Parameter, para4Parameter, para5Parameter);
        }
    
        public virtual ObjectResult<SPT_Get_Role_Button_Result> SPT_Get_Role_Button(string user_ID, string menu_Code)
        {
            var user_IDParameter = user_ID != null ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(string));
    
            var menu_CodeParameter = menu_Code != null ?
                new ObjectParameter("Menu_Code", menu_Code) :
                new ObjectParameter("Menu_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPT_Get_Role_Button_Result>("SPT_Get_Role_Button", user_IDParameter, menu_CodeParameter);
        }
    
        public virtual ObjectResult<SPT_Menus_Result> SPT_Menus(string role_ID)
        {
            var role_IDParameter = role_ID != null ?
                new ObjectParameter("Role_ID", role_ID) :
                new ObjectParameter("Role_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPT_Menus_Result>("SPT_Menus", role_IDParameter);
        }
    
        public virtual ObjectResult<SPT_Menus_User_Result> SPT_Menus_User(string user_ID, string mode)
        {
            var user_IDParameter = user_ID != null ?
                new ObjectParameter("User_ID", user_ID) :
                new ObjectParameter("User_ID", typeof(string));
    
            var modeParameter = mode != null ?
                new ObjectParameter("Mode", mode) :
                new ObjectParameter("Mode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPT_Menus_User_Result>("SPT_Menus_User", user_IDParameter, modeParameter);
        }
    
        public virtual ObjectResult<SPT_Role_One_Result> SPT_Role_One(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPT_Role_One_Result>("SPT_Role_One", iDParameter);
        }
    }
}
