//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Res_Appendix
    {
        public string ID { get; set; }
        public string RES_ID { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<System.DateTime> UPLOAD_TIME { get; set; }
        public Nullable<System.DateTime> ACTIVE_TIME_START { get; set; }
        public Nullable<System.DateTime> ACTIVE_TIME_END { get; set; }
        public string NOTE { get; set; }
        public string CREATEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYID { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string DEL_FLG { get; set; }
        public string TYPE_FLG { get; set; }
        public string FILE_URL { get; set; }
        public byte[] IMAGE { get; set; }
        public string READ_URL { get; set; }
        public int PAGECOUNT { get; set; }
        public string AUTHOR { get; set; }
        public bool IS_FOREVER { get; set; }
    }
}
