//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Resource
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string TYPE_ID { get; set; }
        public string LABEL { get; set; }
        public string NOTE { get; set; }
        public string STATUS { get; set; }
        public string DEL_FLG { get; set; }
        public string SHARE_FLG { get; set; }
        public string CREATEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string MODIFYID { get; set; }
        public Nullable<System.DateTime> MODIFYTIME { get; set; }
        public string INTRODUCTION { get; set; }
        public string ORIGIN_FLG { get; set; }
        public string EXCELLENT_FLG { get; set; }
    }
}
