//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Res_Type
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string CREATEID { get; set; }
        public Nullable<System.DateTime> CREATETIME { get; set; }
        public string BELONG_ID { get; set; }
    }
}
