//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Version
    {
        public string ID { get; set; }
        public string NID { get; set; }
        public string OID { get; set; }
        public string FileName { get; set; }
        public int VERSION_NUM { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
