//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Resource_20160622_bak
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string TYPE_ID { get; set; }
        public string TYPE_NAME { get; set; }
        public Nullable<System.DateTime> UPLOAD_TIME { get; set; }
        public string STATUS { get; set; }
        public string DEL_FLG { get; set; }
        public string LABEL { get; set; }
        public Nullable<decimal> REVIEW_NUM { get; set; }
        public Nullable<decimal> PAGE_VIEW_NUM { get; set; }
        public Nullable<decimal> DOWNLOAD_NUM { get; set; }
        public string INTRODUCTION { get; set; }
        public string NOTE { get; set; }
        public string ORIGIN_FLG { get; set; }
        public Nullable<decimal> PRAISE_PRE { get; set; }
        public string MODIFYID { get; set; }
        public string USER_NAME { get; set; }
        public string CREATEID { get; set; }
        public string CREATE_NAME { get; set; }
    }
}
