//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Homework
    {
        public Z_Homework()
        {
            this.Z_Homework_Comment = new HashSet<Z_Homework_Comment>();
            this.Z_Homework_Student = new HashSet<Z_Homework_Student>();
        }
    
        public string HomeworkId { get; set; }
        public string HomeworkName { get; set; }
        public string TeacherId { get; set; }
        public string ClassId { get; set; }
        public string CourseId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Contents { get; set; }
    
        public virtual ICollection<Z_Homework_Comment> Z_Homework_Comment { get; set; }
        public virtual ICollection<Z_Homework_Student> Z_Homework_Student { get; set; }
    }
}
