//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Homework_Appendix
    {
        public string RecordId { get; set; }
        public string HomeworkId { get; set; }
        public string FILE_NAME { get; set; }
        public string DeleteFlag { get; set; }
        public string TYPE_FLG { get; set; }
        public string FILE_URL { get; set; }
        public byte[] IMAGE { get; set; }
        public string READ_URL { get; set; }
        public Nullable<int> PAGECOUNT { get; set; }
    }
}
