//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_UserPoint
    {
        public string RecordId { get; set; }
        public string UserId { get; set; }
        public string ResourceId { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Point { get; set; }
    }
}
