//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResSharingPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_User
    {
        public string ID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Login_Name { get; set; }
        public string Password { get; set; }
        public string DataRole { get; set; }
        public string PageRole_ID { get; set; }
        public string PageRole_IP_ID { get; set; }
        public string IP { get; set; }
        public string GUID { get; set; }
        public Nullable<int> Link_Count { get; set; }
        public Nullable<System.DateTime> Login_Time { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditMan { get; set; }
        public string Version { get; set; }
        public bool isSeven { get; set; }
        public string SchoolId { get; set; }
        public string Email { get; set; }
        public string SchoolDate { get; set; }
        public string IsCmsAdmin { get; set; }
        public string IsMonitorAdmin { get; set; }
    }
}
